### ISSUE TITLE
Use code generation for roundtrip tests

### ISSUE THREAD

**Issue by krlmlr** [rundel/md4r#5]
The current roundtrip tests read specs and run the tests from the spec. I have had a great experience with generating test code instead. The advantage is that, when a test fails, the failure and the steps to reproduce are easier to see than when going through an indirection.

My DBItest is the prime counterexample. Slowly working on transforming it to generated code.

Happy to help set up infrastructure that worked for me elsewhere.

Reference: https://mtlynch.io/good-developers-bad-tests/ .

**Comment by rundel** [comment]
This totally makes sense - not an option that I had considered and something I am happy to try to implement.

**Comment by krlmlr** [comment]
Happy to assist, this would give me another opportunity to get feedback on the pattern.

**Comment by krlmlr** [comment]
Starting to work on the code generation now.

**Comment by rundel** [comment]
Added via #7
