### ISSUE TITLE
Code in dense bullet lists

### ISSUE THREAD

**Issue by krlmlr** [rundel/md4r#8]
This seems to be the most serious issue with roundtripping `NEWS.md` files at this time. I can work around for now by adding the paragraph myself, a fix would be great, though.

``` r
library(md4r)

md <- "
- `my_fun()` replaces
- `my_fun()` replaces
"

writeLines(to_md(parse_md(md)))
#> - `my_fun()`
#>  replaces
#> - `my_fun()`
#>  replaces
```

<sup>Created on 2024-03-03 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by krlmlr** [comment]
I'm having a hard time manipulating an existing md object. I wonder if we need `$<-.md_node()` and similar methods.

**Comment by rundel** [comment]
I think this should fix the basic issue 

``` r
library(md4r)

md <- "
- `my_fun()` replaces
- `my_fun()` replaces
"

writeLines(to_md(parse_md(md)))
#> - `my_fun()` replaces
#> - `my_fun()` replaces
```

<sup>Created on 2024-03-08 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by rundel** [comment]
Do you have a couple of quick examples of what you'd like to do with `$<-.md_node()`?

**Comment by krlmlr** [comment]
I'd like to tweak the parse tree.

The fix works beautifully!
