### ISSUE TITLE
Backslash before full stop after inline code

### ISSUE THREAD

**Issue by krlmlr** [rundel/md4r#9]
Is this intended? The last substantial roundtrip deviation for fledge's `NEWS.md`, need to review other packages' files too.

``` r
library(md4r)

md <- parse_md("- Test `func()`.")
md
#> md_block_doc [flags: "MD_DIALECT_COMMONMARK"]
#> └── md_block_ul [tight: 1, mark: "-"]
#>     └── md_block_li
#>         ├── md_text_normal - "Test "
#>         ├── md_span_code
#>         │   └── md_text_code - "func()"
#>         └── md_text_normal - "."
writeLines(to_md(md))
#> - Test `func()`\.
```

<sup>Created on 2024-03-10 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by rundel** [comment]
Should be fixed now - its a bit tricky to detect in the AST since escaping needs to be inferred by context, I'm sure there are some edge cases with the current implementation but it doesn't run afoul of any of the existing test cases.
